### PR TITLE
Add an initial object hierarchy

### PR DESCRIPTION
**Pull request by DavidZemon**
Not sure if its too early to talk about the object hierarchy, but I'm going to risk it and say "not too early."

So here's my attempt at some basic structure. I stole this from PropWare because... well... I designed it, so of course I like it. I would think one of the most controversial points will be `hmi` (human-machine interface) because it is lesser known to beginners. But it's the most "correct" term that I know of for describing things like mice, keyboards, monitors, small LCD displays, touchscreens, keypads, buttons, LEDs, etc (anything intended to act as an interface between the prop and a human).

### CODE REVIEW

**Comment by DavidZemon** [comment]
Commit updated to use "pins" instead of "gpio"

**Review by totalspectrum — DISMISSED** [review]
The general architecture looks good. I'm not quite sure about putting i2c, spi, and can under "serial"; they might more naturally be found under "bus". But that's a quibble, since they are in fact serial protocols.

**Comment by DavidZemon** [comment]
I'm well aware that "serial" is too often used to describe specifically UART comms. "bus" seems like it would cause a lot less confusion. I would want "uart" under "bus" too though; are you okay with that?

**Comment by totalspectrum** [comment]
> I'm well aware that "serial" is too often used to describe specifically UART comms. "bus" seems like it would cause a lot less confusion. I would want "uart" under "bus" too though; are you okay with that?

Sure, that sounds OK to me

**Comment by DavidZemon** [comment]
Amended the commit to use `bus` instead of `serial`.

**Comment by DavidZemon** [comment]
FYI @totalspectrum, I configured this repository to remove all "approvals" after new commits are pushed, so a re-approval would be greatly appreciated :)

**Review by totalspectrum — APPROVED** [review]

**Pull request merged**
